canonical/nginx-ingress-integrator-operator

- .gitignore
- lib/charms/nginx_ingress_integrator/v0/ingress.py
- pyproject.toml
- src/charm.py
- tests/unit/test_charm.py
- tox.ini
- Minor styling improvements
- Fix a broken unit test
- Add a unit test for the new interface standard and fix a bug it uncovered
> Ingress interface standard

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- tests/unit/test_library_ingress.py
Add unit tests for `IngressRequires`
> Ingress requires unit tests

- config.yaml
- pyproject.toml
- tests/integration/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_library_ingress.py
- tox.ini
Operator Framework > 1.5.2 is stricter with config values, update so that tests pass.
> Fix tests for ops > 1.5.2

- requirements-dev.txt
Remove unreferenced requirements file
> Remove unnecessary requirements file

- tox.ini
Unpin flake8 and remove E231 and W503 exceptions
> Unpin flake8 and remove ignored rules

- requirements.txt
Upgrade the kubernetes python dependency to a stable version
> Upgrade kubernetes dependency

- src/charm.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
This PR adds integration tests to reflect the changes we've made to the charm recently.
> Expand integration tests

- README.md
Update the README to include project governance details, including code of conduct and getting support links.
> Update README to include project governance details

- metadata.yaml
Add display-name, maintainers and issues fields
> Add additional info to metadata

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- requirements.txt
- tests/unit/test_charm.py
Upgrade kubernetes library to 25.3.0 https://github.com/kubernetes-client/python/releases/tag/v25.3.0
> Upgrade python library for kubernetes

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- src/charm.py
- tests/__init__.py
- tests/integration/__init__.py
- tests/integration/any_charm.py
- tests/integration/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_library_ingress.py
- tox.ini
Add the IngressProxyProvides class for the content-cache-k8s charm to use it.
> add IngressProxyProvides class

- docs/Tutorials/adding-ingress-relation.md
- tests/integration/conftest.py
- tests/integration/test_charm.py
- tests/integration/test_relation.py
Really minor thing that I noticed while using the doc to add Ingress library to GitHub Actions Exporter charm.
Should be updated in the discourse when the workflow is enabled again.
> Fix typo in adding-ingress-relation.md

- README.md
Add badges to check the status of the charm.
List:
- CharmHub Badge
- Publish to edge
- Discourse Status
> docs(ISD-454): Add badges

- docs/Tutorial/getting-started-md
- docs/Tutorial/getting-started.md
- docs/how-to/add-the-ingress-relation.md
- docs/how-to/contribute.md
- docs/how-to/support-multiple-relations.md
- docs/index.md
This PR aims to refactor the charm's docs according to received feedback form the Documentation team.
> Docs refactor

- .licenserc.yaml
- actions.yaml
- charmcraft.yaml
- config.yaml
- docs/how-to/secure-an-ingress-with-tls.md
- metadata.yaml
- pyproject.toml
- tests/__init__.py
- tests/integration/__init__.py
Adding a how-to for TLS certificate usage with the charm. Once this PR is approved, I'll create another one updating the index of the documentation with the appropiate Discourse link.
> adding how-to for tls

- docs/index.md
Add the link to the new TLS how to in the docs index
> modify docs index

- .github/workflows/publish_charm.yaml
Adapt publish workflow to the last changes in https://github.com/canonical/operator-workflows/pull/145
> Adapt publish workflow

- README.md
- docs/index.md
A new section is added to the front page of the documentation to comply with the ISD050 spec.
> Add docs contributing section

- docs/how-to/add-the-ingress-relation.md
- docs/how-to/add-the-nginx-route-relation.md
Add nginx-route relation how-to to the charm.
> Add nginx-route how-to docs

- docs/how-to/add-the-nginx-route-relation.md
Follow up https://github.com/canonical/nginx-ingress-integrator-operator/pull/94
> Add nginx route relation doc updates

- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
Make NginxRouteRequirer public so that data contained in it can be accessed by the requirer charms
N/A
N/A
N/A
nginx_route.py
> Make NginxRouteRequirer public

- src/charm.py
Applicable spec: N/A
Trivial change renaming `get_additional_hostnames` to `get_all_hostnames` to more accurately reflect what it does.
More accurately reflect function.
N/A
N/A
N/A
> Rename get_additional_hostnames to reflect what it does

- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tox.ini
Automated action to fetch latest version of charm libraries. The branch of this PR
will be wiped during the next check. Unless you really know what you're doing, you
most likely don't want to push any commits to this branch.
> Update charm libraries

- .github/workflows/integration_test_arm64.yaml
- README.md
Update README according to the new template.
> Update README file

- .github/workflows/promote_charm.yaml
Currently it is using by default 20.04, which is not being updated.
> Update base-channel in promote_charm.yaml

- .github/workflows/terraform-docs.yaml
- .github/workflows/test_terraform_files.yaml
- docs/changelog.md
- terraform/.tflint.hcl
- terraform/README.md
- terraform/main.tf
- terraform/outputs.tf
- terraform/variables.tf
- terraform/versions.tf
Add terraform module.
Deploy nginx via terraform.
> Add terraform module
