- lib/charms/nginx_ingress_integrator/v0/ingress.py
Currently this isn't correctly rendered as a list on charmhub per https://charmhub.io/nginx-ingress-integrator/libraries/ingress. Having talked with the web and design team, they've suggested it's because of the indentation, so remove that so this is correctly rendered as a list.
> Update indentation on library docstring so it's rendered as a list

- lib/charms/nginx_ingress_integrator/v0/ingress.py
In the previous change we updated the docstring for the charm library to fix formatting of lists. I had mistakenly thought that when you published a new version of the charm that library would be updated as well. It turns out you need to run `charmcraft publish-lib` specifically, so I'm incrementing the patch number here to allow me to do that.
> Increment patch level so a new library version can be published

- config.yaml
- src/charm.py
- tests/unit/test_charm.py
Addresses https://github.com/canonical/nginx-ingress-integrator-operator/issues/13.
I believe this would only ever be a deploy-time option, so it's not been exposed as an option in the relation. That could obviously be changed in the future though.
> Add whitelist-source-range annotation based on config entry

- README.md
- metadata.yaml
With the `assumes` entry in metadata.yaml we can ensure this charm isn't deployable on machine models even if it doesn't have a container.
This means we no longer need the placeholder workload container.
Has been tested to not be deployable on machine models (with juju > 2.9.23). Need to test a charm upgrade from existing to this version, but currently blocked on https://bugs.launchpad.net/juju/+bug/1991511.
> Update charm to not require a workload resource

- .woke.yml
- README.md
- check_woke.sh
- metadata.yaml
- tox.ini
Add a tox target for 'woke' to check for inclusive naming in the charm.
Since this is provided by a snap, we're creating a shell command to check you have the snap installed or error out, and then run the woke command.
This isn't yet hooked up to workflows, as this charm doesn't have those yet.
> Add a tox target for 'woke' to check for inclusive naming in the charm

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement_proposal.yml
- .github/workflows/comment.yaml
- .github/workflows/integration_test.yaml
- .github/workflows/on_push.yaml
- .github/workflows/publish_branch.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- tox.ini
Pull in github workflows for initial CI setup.
For now this isn't running the `woke` target, because we'll need to install the `woke` snap for that to work, which will require some changes to operator-workflows. This also doesn't yet include static code analysis with bandit, that will come in a later PR.
> Set up github workflows

- tox.ini
Run our inclusive naming checks as part of the `lint` target. This will mean it's triggered on every CI run.
> Add our check for inclusive naming to the lint target so it will happen on every CI run

- pyproject.toml
- tox.ini
Update pyproject.toml so that we're including missing lines in test coverage output and failing if we're under a specified percentage - pin to the current test coverage, which is 93%.
> Add missing lines to test coverage and fail under specified percentage

- charmcraft.yaml
- src/charm.py
- tests/integration/conftest.py
There's currently no good way to have a different series of a k8s charm in edge and stable, and be able to test upgrades from one to another (see https://bugs.launchpad.net/juju/+bug/1996590). So let's revert to focal for now. We bumped it up to jammy due to build failures on focal that have since been resolved.
> Revert to focal as k8s charm series upgrades aren't well handled currently

- lib/charms/nginx_ingress_integrator/v0/ingress.py
We need to increment the version number so this can be published, and charmhub has a limitation on the minor version number which means we're forced to increment `LIBAPI` (it only allows `LIBPATCH` to go up to 10)
> Add copyright info to library, and increment version number

- config.yaml
- lib/charms/nginx_ingress_integrator/v0/ingress.py
- src/charm.py
- tests/integration/conftest.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
- tox.ini
If owasp-modsecurity-crs is set to True, you can add custom rules via owasp-modsecurity-custom-rules.
Command example:
```bash
juju config nginx-ingress-integrator owasp-modsecurity-custom-rules='SecAction "id:900130,phase:1,nolog,pass,t:none,setvar:tx.crs_exclusions_wordpress=1"\n'
```
This PR adds:
- owasp-modsecurity-custom-rules new config
- unit test
- integration test
> Add owasp-modsecurity-custom-rules config

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- tox.ini
The previously published version of the library was 0.10. This set it to 0.11 which can be published (have already done so).
This means no-one needs to update charm code to get the new version, they can simply update the existing v0.
> Revert to publishable library version

- README.md
- tox.ini
Some documentation updates based on feedback from the docs team. The deployment section has been moved to discourse-based documentation.
> Remove deployment section from readme, add links to juju, charms and ingress controller per feedback from docs team

- src/charm.py
- tests/unit/test_charm.py
nginx-ingress-integrator reports kubernetes livrary version in juju status
Example (nginx1):
> fix(ISD-359): Add kubernetes library version to status message

- pyproject.toml
- src/charm.py
- tests/integration/any_charm.py
- tests/integration/conftest.py
- tests/integration/test_charm.py
- tests/integration/test_relation.py
- tests/unit/test_charm.py
- tests/unit/test_library_ingress.py
- tox.ini
Fix #4 
This PR:
- Add a mechanism that for every event, checks if there are unused services or ingress and delete them. 
This is done by:
1) getting all services/ingress resources with the label "app.juju.is/created-by=".
2) getting all services/ingress resources from config or relations 
3) Each service/ingress resource that is not in the list mentioned above is deleted.
- Add unit and integration tests
- Add mypy checker and related fixes or disabled types
- Change AnyCharm to get Ingress values from the relation, if exists. The default values were set in the _\_init_\_ and since charm is a stateless application, every event was initializing the charm and recreating the ingress with the default values. Reference [here](https://juju.is/docs/sdk/create-a-minimal-kubernetes-charm#heading-- …
> fix(ISD-362): Remove unused resources

- docs/Tutorials/adding-ingress-relation.md
- src/charm.py
- tests/integration/conftest.py
- tests/integration/test_relation.py
- tests/unit/test_charm.py
- tox.ini
This PR focuses on the creation of a custom label for both services and ingresses, to not be dependant on the `app.juju.is/created-by=` label.
> Adding custom labels

- config.yaml
- src/charm.py
- tests/unit/test_charm.py
An application might have long-running operations that need more time to finish. The default proxy_read_timeout is 60s so if you need more than that and don't increase it, NGINX will give a 504 (Gateway Timeout) error.
This PR adds a new configuration to set proxy-read-timeout so it can be changed as required.
proxy-read-timeout: Defines a timeout in seconds for reading a response from the proxied server.
Reference [here](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-timeouts).
> feat(ISD-482): Add proxy-read-timeout configuration

- .github/workflows/test_and_publish_charm.yaml
The integration test workflow from operator-workflows run multiple test modules in the same model. 
This behavior causes problems in the `test_delete_unused_ingresses` test case, since there will be some ingress resource residues from previous test runs.
> Fix the publish charm workflow

- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
The current `LIBID` in the `nginx_route` charm library is incorrect and it causes the publish-lib to fail.
> Update the LIBID in nginx_route charm library

- .github/workflows/test_and_publish_charm.yaml
Remove the module `test_charm` from the integrations tests. It doesn't exist anymore
> Fix release pipeline

- config.yaml
- pyproject.toml
- src/charm.py
- src/helpers.py
- tests/integration/test_nginx_route.py
- tests/unit/test_charm.py
Add backend-protocol  configuration.
Default: HTTP
Valid values: "HTTP", "HTTPS", "GRPC", "GRPCS", "AJP", "FCGI"
Reference: [Ingress User Guide](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol ).
> feat(ISD-616): Add backend-protocol configuration (#59)

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
This PR is a follow-up of https://github.com/canonical/nginx-ingress-integrator-operator/pull/66
> fix(ISD-616): Add backend-protocol configuration to the libraries

- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
- tests/conftest.py
Update the documentation of the nginx-route library to avoid the recommendation that the local charm has an `external-hostname` (or similar) config option that it passes to the nginx-ingress-integrator charm over the relation. Instead, default to `self.app.name` and let this be overridden using the `service-hostname` option of the nginx-ingress-integrator charm.
This means the local charm can have one less config option, but still uses the best practice of defaulting to the deployed application name.
> Update documentation for nginx-route library to avoid needing config for external hostname

- lib/charms/nginx_ingress_integrator/v0/ingress.py
Similarly to https://github.com/canonical/nginx-ingress-integrator-operator/pull/83 update the documentation of the ingress library to avoid the recommendation that the local charm has an external-hostname (or similar) config option that it passes to the nginx-ingress-integrator charm over the relation. Instead, default to self.app.name and let this be overridden using the service-hostname option of the nginx-ingress-integrator charm.
This means the local charm can have one less config option, but still uses the best practice of defaulting to the deployed application name.
Note that this library/relation doesn't yet implement the "ingress" relation as defined in the charm-relation-interfaces project. This update doesn't change that, but that will be addressed in future changes, at which …
> Update documentation for ingress library to avoid needing config for external hostname

- src/charm.py
- tests/unit/test_charm.py
We need to set `ActiveStatus` in the `start` event because this is a workload-less charm, so there's no `pebble-ready` event to react to. This means this is the only event (outside of `update-status`) that is fired if a pod is restarted by the k8s cluster. If we don't do anything here the charm would remain in maintenance status.
> Handle the start event

- .github/workflows/integration_test.yaml
- src/charm.py
- tests/integration/test_zero_downtime.py
- tests/unit/test_charm.py
This PR introduces the ability for mission-critical applications to seamlessly upgrade from the legacy `ingress` relation to the `nginx-route` relation without experiencing any downtime.
For applications opting to use this zero downtime transition:
1. The application should first prepare an intermediate revision that supports both `ingress` and `nginx-route` relations.
2. Upgrade the application charm to this intermediate revision.
3. Establish the `nginx-route` relation with the same relation data to `nginx-ingress-relation` while retaining the legacy `ingress` relation.
4. Ensure that all operations and processes are idle.
5. Safely remove the legacy `ingress` relation.
6. Refresh the application charm to the revision that exclusively supports `nginx-route`.
By following this sequence, …
> Support zero downtime upgrade from legacy ingress relation to nginx-route relation

- src/charm.py
When the `relation-broken` event is triggered, there's a possibility that the broken relation, although listed, the remote application may not be accessible. This update ensures such relations are safely ignored.
Fix: https://github.com/canonical/nginx-ingress-integrator-operator/issues/90
> Ignore broken relations during relation-broken events

- .github/workflows/test.yaml
- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
Switch to using edge self-hosted runners so that we use the edge runners in our team before they are rolled out more broadly
> Switch to edge runners

- src/controller.py
- src/ingress_definition.py
- tests/unit/test_ingress.py
Certain versions of the Nginx ingress controller are unable to resolve the endpoints of a service when the port names in the service definition and endpoints definition differ. To address this, update the charm to ensure the port names align across all ingress related objects.
> Match port names across ingress related objects

- charmcraft.yaml
The `nginx-ingress-integrator` charm is using pure Python, thereby it *should* compatibility with arm64 architectures. This pull request introduces the declarations to enable deployment on arm64 machines.
> Update charmcraft.yaml to declare arm64 support

- actions.yaml
- charmcraft.yaml
- config.yaml
- lib/charms/nginx_ingress_integrator/v0/ingress.py
- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- src/helpers.py
- tests/__init__.py
- tests/conftest.py
- tests/integration/__init__.py
- tests/integration/any_charm.py
- tests/integration/any_charm_nginx_route.py
- tests/integration/conftest.py
- tests/integration/test_nginx_route.py
- tests/integration/test_relation.py
- tests/integration/test_zero_downtime.py
- tests/unit/test_charm.py
- tests/unit/test_library_ingress.py
- tox.ini
Applicable spec: N/A
Type hint the lib to pass linting.
Pass linting tests.
None.
None.
Added type hint.
> fix: lib lint type hints, update license year

- lib/charms/nginx_ingress_integrator/v0/ingress.py
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- requirements.txt
- src/charm.py
- src/ingress_definition.py
- src/tls_relation.py
- tests/integration/provider_charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py
- tests/integration/provider_charm/src/charm.py
- tests/unit/test_cert_relation.py
Upgrade the TLS Certificates library to v3. Also inject the full chain in the K8S secret instead of only the certificates.
When a certificates uses intermediate certificate the chain be stored in the secret for Nginx to provide a valid certificate chain to the user
N/A
Due to some event changed, I had to adapt the `get_hostname_from_csr` to `get_hostname_from_cert` as CSR wasn't available anymore in some events.
Upgraded TLS Certificate library
> Upgrade to v3 and get full cert chain

- .github/workflows/test.yaml
- src/charm.py
- tests/unit/test_cert_relation.py
Applicable spec: n/a
Check that charm can see remote units of the ingress relationship before proceeding.
Fix #140 
If you deploy tls at the same time as ingress (e.g. using the terraform provider), nginx-ingress will fail in the `certificates-relation-created` hook and not recover.
The reason is explained in https://github.com/canonical/nginx-ingress-integrator-operator/issues/140#issuecomment-2133931059, that certificates-relation-created is fired before ingress-relation-joined, and the charm sees no units in the relation, causing an error in `ingress_definition.IngressDefinitionEssence.upstream_endpoints`:
```
unit-nginx-ingress-integrator-0: 13:59:56 ERROR unit.nginx-ingress-integrator/0.juju-log certificates:51: Uncaught exception while in charm code:
Traceback (most recent call …
```
> Add check for remote units before considering ingress relation ready

- src/charm.py
not using `get()` will result in KeyError being raised if no certificate is found for the required hostname, masking the intended fail message.
> use dict.get() to fetch cert

- charmcraft.yaml
According to https://juju.is/docs/sdk/charmcraft-yaml, aarch64 is not one of the archs that is supported. arm64 is though!
> fix: remove unsupported arch

- .github/workflows/integration_test_arm64.yaml
- .github/workflows/publish_charm.yaml
- .github/workflows/publish_charm_arm64.yaml
- tests/conftest.py
- tests/integration/conftest.py
- tox.ini
We want to build and publish an arm64 charm for the `nginx-integrator`.
For the integration tests to work, an arm64 version of `any-charm` is needed. Added in https://github.com/canonical/any-charm/pull/23
> Publish also arm64 architecture

- .github/workflows/publish_charm_arm64.yaml
The input variable `integration-test-workflow-file` was not after a `with:`.
> Fix arm64 publish

- .github/workflows/promote_charm.yaml
Allow choosing the architecture for the promote github action, so arm64 can be promoted to stable.
> Allow choosing architecture for promoting

- src/charm.py
- src/ingress_definition.py
- tests/unit/test_status.py
- tox.ini
Applicable spec: n/a
Provide more specific blocking status to indicate missing IP and log stack trace.
We had to troubleshoot a production issue where the ip was missing in the databag. The current blocked state was not so helpful, we saw relation data but did not spot the missing ip or were not aware that this is required. 
Providing a more specific blocked status message should help users of the charm.
n/a
n/a
n/a
> Provide more specific blocked status msg to indicate missing IP

- .github/workflows/integration_test.yaml
- .github/workflows/integration_test_arm64.yaml
- config.yaml
- src/controller/ingress.py
- src/ingress_definition.py
- tests/unit/test_cert_relation.py
- tests/unit/test_ingress.py
- tox.ini
Add the `proxy-send-timeout` and `proxy-connect-timeout` charm configurations to adjust the ingress timeout.
The default values are taken from the corresponding NGINX configuration defaults.
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout
Fix: https://github.com/canonical/nginx-ingress-integrator-operator/issues/164
> Add the `proxy-send-timeout` and `proxy-connect-timeout` options

- .github/workflows/integration_test_arm64.yaml
- charmcraft.yaml
- requirements.txt
- src/charm.py
- src/ingress_definition.py
- tests/integration/conftest.py
- tests/integration/test_cert_relation.py
- tests/integration/test_nginx_route.py
Use the full certificate chain from the `tls-certificates` relation instead of only the leaf certificate.
> Use the full certificate chain from the tls-certificates relation for ingress

- docs/changelog.md
- docs/explanation/security.md
Docs only change.
Add security explanation docs.
The [OWASP ModSecurity Core Rule Set](https://coreruleset.org/) will be covered in a separate docs task, a story for this in added in backlog.
> Add security explanation docs

- .github/workflows/integration_test.yaml
- .github/workflows/integration_test_arm64.yaml
- CODEOWNERS
Replace references to is-charms to platform-engineering in CODEOWNERS
> Use new team name in CODEOWNERS

- README.md
- docs/explanation/roadmap.md
- docs/how-to/add-the-nginx-route-relation.md
- docs/index.md
- docs/reference/external-access.md
Update the documentation by removing deprecated pages, and link Security in the table of content.
> Isd 4178 nginx ingress integrator operator update index.md and remove roadmap.md
